// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIDStandardization.Data.Context;

#nullable disable

namespace PIDStandardization.Data.Migrations
{
    [DbContext(typeof(PIDDbContext))]
    [Migration("20260118120000_RemoveBlockMappings")]
    partial class RemoveBlockMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model snapshot after removing BlockMappings - matches current PIDDbContextModelSnapshot
            // (BuildTargetModel content omitted for brevity - EF will regenerate this)
#pragma warning restore 612, 618
        }
    }
}
