// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIDStandardization.Data.Context;

#nullable disable

namespace PIDStandardization.Data.Migrations
{
    [DbContext(typeof(PIDDbContext))]
    partial class PIDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIDStandardization.Core.Entities.Drawing", b =>
                {
                    b.Property<Guid>("DrawingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrawingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrawingTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Revision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("DrawingId");

                    b.HasIndex("ProjectId", "DrawingNumber")
                        .IsUnique();

                    b.ToTable("Drawings");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DesignPressure")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DesignPressureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DesignTemperature")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DesignTemperatureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("DownstreamEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DrawingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("FlowRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlowRateUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OperatingPressure")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OperatingPressureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("OperatingTemperature")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OperatingTemperatureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PowerOrCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PowerOrCapacityUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceBlockName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecificationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UpstreamEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EquipmentId");

                    b.HasIndex("DownstreamEquipmentId");

                    b.HasIndex("DrawingId");

                    b.HasIndex("UpstreamEquipmentId");

                    b.HasIndex("ProjectId", "TagNumber")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Instrument", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accuracy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalibrationFrequency")
                        .HasColumnType("int");

                    b.Property<Guid?>("DrawingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstrumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoopNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputSignal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProcessConnection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RangeMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RangeMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Units")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstrumentId");

                    b.HasIndex("DrawingId");

                    b.HasIndex("LineId");

                    b.HasIndex("ParentEquipmentId");

                    b.HasIndex("ProjectId", "TagNumber")
                        .IsUnique();

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Line", b =>
                {
                    b.Property<Guid>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DesignPressure")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DesignPressureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DesignTemperature")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DesignTemperatureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("DrawingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FluidType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FromEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("InsulationRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InsulationThickness")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InsulationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Length")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LineNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LineSpecId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NominalSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipeSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ToEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LineId");

                    b.HasIndex("DrawingId");

                    b.HasIndex("FromEquipmentId");

                    b.HasIndex("ToEquipmentId");

                    b.HasIndex("ProjectId", "LineNumber")
                        .IsUnique();

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TaggingMode")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectName");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.ValidationRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("RuleId");

                    b.HasIndex("RuleCode")
                        .IsUnique();

                    b.ToTable("ValidationRules");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Drawing", b =>
                {
                    b.HasOne("PIDStandardization.Core.Entities.Project", "Project")
                        .WithMany("Drawings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Equipment", b =>
                {
                    b.HasOne("PIDStandardization.Core.Entities.Equipment", "DownstreamEquipment")
                        .WithMany("UpstreamConnections")
                        .HasForeignKey("DownstreamEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PIDStandardization.Core.Entities.Drawing", "SourceDrawing")
                        .WithMany("Equipment")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PIDStandardization.Core.Entities.Project", "Project")
                        .WithMany("Equipment")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIDStandardization.Core.Entities.Equipment", "UpstreamEquipment")
                        .WithMany("DownstreamConnections")
                        .HasForeignKey("UpstreamEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DownstreamEquipment");

                    b.Navigation("Project");

                    b.Navigation("SourceDrawing");

                    b.Navigation("UpstreamEquipment");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Instrument", b =>
                {
                    b.HasOne("PIDStandardization.Core.Entities.Drawing", "Drawing")
                        .WithMany()
                        .HasForeignKey("DrawingId");

                    b.HasOne("PIDStandardization.Core.Entities.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PIDStandardization.Core.Entities.Equipment", "ParentEquipment")
                        .WithMany()
                        .HasForeignKey("ParentEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PIDStandardization.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawing");

                    b.Navigation("Line");

                    b.Navigation("ParentEquipment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Line", b =>
                {
                    b.HasOne("PIDStandardization.Core.Entities.Drawing", "Drawing")
                        .WithMany()
                        .HasForeignKey("DrawingId");

                    b.HasOne("PIDStandardization.Core.Entities.Equipment", "FromEquipment")
                        .WithMany()
                        .HasForeignKey("FromEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PIDStandardization.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIDStandardization.Core.Entities.Equipment", "ToEquipment")
                        .WithMany()
                        .HasForeignKey("ToEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Drawing");

                    b.Navigation("FromEquipment");

                    b.Navigation("Project");

                    b.Navigation("ToEquipment");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Drawing", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Equipment", b =>
                {
                    b.Navigation("DownstreamConnections");

                    b.Navigation("UpstreamConnections");
                });

            modelBuilder.Entity("PIDStandardization.Core.Entities.Project", b =>
                {
                    b.Navigation("Drawings");

                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
